#!/usr/bin/env bash
# Builds the final ISO. Needs to run on an Arch-based Linux machine
# (CachyOS works) with the `archiso` package installed, plus Docker
# (or Podman) for the one-time qemu-macos build — this doesn't run
# inside this sandbox, it's meant to run on your own machine.
set -euo pipefail
cd "$(dirname "$0")"
WORKDIR="${1:-./work}"
OUTDIR="${2:-./out}"

# ---------------------------------------------------------------------------
# Build mode: `release` (default -- the clean build for normal use) or `debug`
# (the verbose OpenCore image additionally ships serial kernel logging + a
# public DEBUG OpenCore so a stuck macOS boot can be traced on the serial log;
# see patch-opencore-verbose.sh / README.md). ONLY the verbose image differs --
# `verbose off` is identical in both modes. Set it non-interactively with
# `LAYEROSX_MODE=debug ./build.sh`, or pick it at the prompt below.
# ---------------------------------------------------------------------------
MODE="${LAYEROSX_MODE:-}"
if [ -z "$MODE" ]; then
    if [ -t 0 ]; then
        echo "LayerOSX build mode?"
        echo "  1) release  -- clean build for normal use (default)"
        echo "  2) debug    -- verbose image logs the kernel to serial for troubleshooting"
        read -r -p "Select [1/2, Enter=release]: " _m || _m=""
        case "$_m" in
            2|debug|d|D) MODE="debug" ;;
            *)           MODE="release" ;;
        esac
    else
        MODE="release"
    fi
fi
case "$MODE" in
    debug|release) : ;;
    *) echo "build.sh: unknown LAYEROSX_MODE='$MODE' -- using release." >&2; MODE="release" ;;
esac
export LAYEROSX_MODE="$MODE"
echo "==================================================================="
echo "  LayerOSX build mode: $MODE"
[ "$MODE" = "debug" ] && echo "  (verbose image ships serial kernel logging + DEBUG OpenCore)"
echo "==================================================================="
# Bake the chosen mode into the image so the RUNTIME launcher can pick
# mode-appropriate defaults (release: verbose off / audio on / Reims on;
# debug: verbose on / VMware / audio off -- see mac-vm-launch.sh). A plain
# marker file the launcher reads; the live-ISO rootfs (and the installed
# system rsynced from it) both carry it. Regenerated every build, gitignored.
mkdir -p airootfs/etc/layerosx
printf '%s\n' "$MODE" > airootfs/etc/layerosx/mode

# Maintenance terminal (F2) policy, independent of the mode so any build can
# ship with or without it -- just set LAYEROSX_TERMINAL:
#   password -> F2 asks for the kiosk user's password, then opens the terminal
#   open     -> F2 opens the terminal directly (no password)
#   off      -> no terminal at all (fully locked appliance)
# Default follows the mode: debug=open, release=password. Baked like the mode
# (airootfs/etc/layerosx/terminal, gitignored), read by lib/maint-terminal.sh.
TERMINAL="${LAYEROSX_TERMINAL:-}"
if [ -z "$TERMINAL" ]; then
    [ "$MODE" = debug ] && TERMINAL=open || TERMINAL=password
fi
case "$TERMINAL" in
    password|open|off) : ;;
    *) echo "build.sh: unknown LAYEROSX_TERMINAL='$TERMINAL' -- using password." >&2; TERMINAL=password ;;
esac
printf '%s\n' "$TERMINAL" > airootfs/etc/layerosx/terminal
echo "  Maintenance terminal (F2): $TERMINAL"

# Kiosk VT-switch lock (release only). Ctrl+Alt+F1..F6 (switch to a text
# console) and Ctrl+Alt+Backspace (zap X) are the last host shortcuts openbox
# can't disable -- they're X-server options. A release build is a locked
# appliance, so turn them off; a debug build keeps them so the developer can
# still reach tty2 / kill X while troubleshooting. Baked into airootfs, gitignored.
_vtlock=airootfs/etc/X11/xorg.conf.d/10-layerosx-kiosk-lock.conf
if [ "$MODE" = release ]; then
    mkdir -p airootfs/etc/X11/xorg.conf.d
    cat > "$_vtlock" <<'CONF'
# Generated by build.sh for a RELEASE (locked-kiosk) build. Disables VT
# switching (Ctrl+Alt+Fn) and Ctrl+Alt+Backspace so there is no host-side
# escape from the fullscreen VM. A debug build omits this file.
Section "ServerFlags"
    Option "DontVTSwitch" "on"
    Option "DontZap"      "on"
EndSection
CONF
else
    rm -f "$_vtlock"
fi

command -v mkarchiso >/dev/null 2>&1 || {
    echo "mkarchiso not found — install the 'archiso' package first (sudo pacman -S archiso)." >&2
    exit 1
}

# Build-host tools used to derive the OpenCore boot variants below (verbose
# boot and the AMD_Vanilla-patched image): qemu-img for the qcow2<->raw
# round-trip, mtools to edit the FAT EFI partition without root. Auto-install
# the missing ones so the build doesn't silently ship without a variant just
# because a tool wasn't there -- easy to forget. Best-effort: if the install
# can't run (no network, no sudo, a non-pacman distro), we don't abort the
# build; each patch step degrades to a clear warning on its own.
_missing=()
command -v qemu-img >/dev/null 2>&1 || _missing+=("qemu-img")
command -v mcopy    >/dev/null 2>&1 || _missing+=("mtools")
if [ "${#_missing[@]}" -gt 0 ]; then
    if command -v pacman >/dev/null 2>&1; then
        echo "==> installing missing build tools for verbose-boot patching: ${_missing[*]}"
        sudo pacman -S --needed --noconfirm "${_missing[@]}" ||             echo "WARNING: couldn't auto-install ${_missing[*]} -- the ISO may ship without the verbose and/or AMD OpenCore images. Install them by hand and re-run to build those variants." >&2
    else
        echo "WARNING: ${_missing[*]} missing and this isn't a pacman system -- install them by hand to build the verbose and AMD OpenCore images." >&2
    fi
fi

# Checking just the binary isn't enough: confirmed on real hardware
# that an ISO built from an already-existing qemu-system-x86_64 (from
# before the libjpeg.so.62 bundling fix, see README.md) kept shipping
# the old broken binary forever, since this check never noticed
# anything was missing and never re-ran prepare-qemu-macos.sh. The
# bundled runtime libraries are just as required as the binary itself
# now, so check for both.
if [ ! -x airootfs/opt/layerosx/bin/qemu-system-x86_64 ] || \
   [ ! -d airootfs/opt/layerosx/lib ] || \
   [ -z "$(ls -A airootfs/opt/layerosx/lib 2>/dev/null)" ]; then
    echo "No pre-built qemu-system-x86_64 (or its bundled runtime libraries) yet — building it now (Docker, real QEMU source build, 30-60+ min)."
    ./prepare-qemu-macos.sh
fi

# Same idea as the qemu-system-x86_64 check above: without OpenCore.qcow2
# staged, mac-vm-launch.sh has nothing to attach as the boot disk and
# macOS's kernel will never come up on plain OVMF alone (see
# prepare-opencore.sh and README.md for why). This one's just a download
# (no Docker build), so it's quick.
if [ ! -s airootfs/opt/layerosx/opencore/OpenCore.qcow2 ]; then
    echo "No OpenCore boot image yet — staging it now."
    ./prepare-opencore.sh
fi

# Derive every OpenCore boot variant from the pristine, checksum-verified
# OpenCore.qcow2 that prepare-opencore.sh stages -- as SEPARATE images, so the
# verified base is never mutated. mac-vm-launch.sh then picks one at launch by
# host CPU vendor (Intel vs AMD) and the `verbose` toggle:
#   OpenCore.qcow2             Intel, clean Apple-logo boot   (the base)
#   OpenCore-verbose.qcow2     Intel, verbose (-v) boot log
#   OpenCore-amd.qcow2         AMD  (AMD_Vanilla kernel patches), clean boot
#   OpenCore-amd-verbose.qcow2 AMD  (AMD_Vanilla kernel patches), verbose
# Why AMD needs its own image: XNU is Intel-only and panics/hangs at
# EXITBS->HANDOFF on an AMD CPU without the AMD_Vanilla patches, but those same
# patches would corrupt a correct kernel on Intel -- so they must live in a
# separate image the launcher hands only to AMD hosts. All steps are idempotent
# and always re-run (a reused base from an earlier build is exactly why baking
# these only in prepare-opencore.sh's download path could silently ship
# stale/missing variants). Each degrades to a clear warning if qemu-img/mtools
# are missing rather than aborting the build.
OCDIR=airootfs/opt/layerosx/opencore
# First, fix a latent bug in the base image itself (in place): its config.plist
# enables several kexts that aren't actually bundled (VoodooPS2Controller etc.),
# which makes OpenCore HALT on "missing injected kext" before macOS ever loads.
# This must run before the derivations so every image -- including the clean
# Intel base that boots directly -- inherits the fix. Idempotent.
./patch-opencore-fixup.sh   "$OCDIR/OpenCore.qcow2"
./patch-opencore-verbose.sh "$OCDIR/OpenCore.qcow2"     "$OCDIR/OpenCore-verbose.qcow2"
./patch-opencore-amd.sh     "$OCDIR/OpenCore.qcow2"     "$OCDIR/OpenCore-amd.qcow2"
./patch-opencore-verbose.sh "$OCDIR/OpenCore-amd.qcow2" "$OCDIR/OpenCore-amd-verbose.qcow2"

# mkarchiso reuses $WORKDIR across runs and does NOT reliably notice
# when profiledef.sh/pacman.conf/packages.x86_64 changed — it can
# silently skip re-copying them and build with stale config (seen
# firsthand: it kept ignoring a newly added pacman repo). Package
# downloads are cached separately by pacman itself (CacheDir, usually
# /var/cache/pacman/pkg/), so clearing this directory doesn't mean
# re-downloading everything — just a fresh airootfs assembly. Safer to
# always start clean.
sudo rm -rf "$WORKDIR"

# Old ISOs otherwise just pile up in here forever: profiledef.sh names
# each one after today's date (iso_version), so nothing ever gets
# overwritten and it's easy to run a stale ISO by mistake without
# noticing (confirmed in practice: three different days' ISOs sitting
# side by side, only the newest actually had the latest fixes). Clean
# it the same way $WORKDIR already is, so $OUTDIR only ever has the
# ISO from the build that just ran.
sudo rm -rf "$OUTDIR"

# Belt-and-suspenders on top of profiledef.sh's file_permissions
# (which is what actually matters for the final ISO): if this repo is
# checked out on a Windows-mounted drive (common under WSL), the
# executable bit git tracked doesn't reliably survive onto disk —
# found the hard way when install-wizard.sh landed on a built ISO as
# 644 despite being 755 in the git index. Re-assert it on every build
# so a newly added script that forgets a profiledef.sh entry still
# works, instead of silently shipping non-executable.
find airootfs -name '*.sh' -exec chmod +x {} \;

sudo mkarchiso -v -w "$WORKDIR" -o "$OUTDIR" .
echo "ISO ready in $OUTDIR/ — drag it onto your Ventoy drive."
